name: CI

on:
  push: 
    branches: ['master']
  pull_request:
    branches: ['master']
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm i -g pnpm@9.10.0
      - run: pnpm i
      - run: pnpm run build