name: CI / Deploy to GHCR

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  call-ghcr-workflow:
    uses: offensive-vk/Assets/.github/workflows/ghcr.yml@master
    with:
      author: "Vedansh"
      title: "auto-user-activity"
      description: "Fetch and Updates Your Readme Markdown with the Recent GitHub activity of a github user."
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}