name: CI / Recent Activity

on:
  workflow_dispatch:

jobs:
  update_activity:
    name: Update Logs
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add Latest Activity to File
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
        with:
          committer: Hamster [bot]
          committer-email: TheHamsterBot@outlook.com
          commit-msg: |
            🧑‍💻 Updated Recent Activity


            Signed-off-by: Hamster [bot] <TheHamsterBot@outlook.com>
            Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          max-lines: 150
          target-file: './RECENT.md'
